version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - ghcr.io/${GITHUB_REPOSITORY_OWNER?VARIABLE NOT SET}/dummy:latest
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER?VARIABLE NOT SET}/dummy:latest
        
